export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const DELETE_ACCESS_TOKEN = "DELETE_ACCESS_TOKEN";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_PROFILE_DATA = "SET_PROFILE_DATA";
export const SET_STATUS_LIST = "SET_STATUS_LIST";

